#!/bin/bash
TYPE=$1
if [[ -z $TYPE ]] ; then
    echo "release [major|minor|patch]"
    exit 1
fi
echo "Bump version"
npm version $TYPE
echo "Updating version in program"
./tools/update-version
npm publish
