#!/bin/bash
VERSION=$(jq -r '.version' package.json)
perl -i.bak -pe "s/const version = .*$/const version = '$VERSION';/gm" bin/typeloy.ts
GIT_TAG=$(git describe --tags --abbrev=0)
git tag -f $GIT_TAG
